knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
       
        google:
            type: google
            # add and set these environment variables in your .env files
            client_id: '%env(resolve:GOOGLE_CLIENT_ID)%'
            client_secret: '%env(resolve:GOOGLE_CLIENT_SECRET)%'

            # a route name you'll create
            redirect_route: connect_google_check
            redirect_params: {}
            # whether to check OAuth2 "state": defaults to true
            # use_state: true

